apiVersion : apps/v1
kind: Deployment
metadata:
  name: "qubeaks-961b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "qubeaks-961b"
  template:
    metadata:
      labels:
        app: "qubeaks-961b"
    spec:
      containers:
        - name: "qubeaks-961b"
          image: "qubepo.azurecr.io/qubeaks"
          ports:
          - containerPort: 3000